### ISSUE TITLE
USB PCAP dump of HX870E firmware update and data read/write

### ISSUE THREAD

**Issue by cr** [johannessen/hx870#1]
Hi Arne,

 I have made some progress in reverse-engineering the USB protocol for HX870 firmware update, data read, and data write. The long-term goal is to implement those protocols in Python to gain a bit more flexibility in managing and hacking the devices.

As a short short term goal I am particularly interested in a differential analysis between US and EU models. So far I have some tooling for analyzing and dumping the USB traffic from .pcapng files. It would be super helpful if I could get access to USB pcap dumps from a EU model. Would you be able to provide me with those? I'd happily provide instructions for that, and all it really takes is a Wireshark installation and 20 minutes time.

Preliminary analysis shows that the raw firmware image of the US model seems to contain all the ATIS functionality. Switching between US and EU models might just be down to flipping a few bytes in flash (and I am sure that Yaesu's original programming software prevents just that).

Best,
cr

**Comment by johannessen** [comment]
Hi Christiane,

thanks for getting in touch. Reverse engineering the USB protocol sounds like a great idea! I'd love to help, but I keep the radio on my boat and won't be anywhere near it until some time in February. Not sure if that's short term enough?

Also, I never used Wireshark, so your instructions would surely be helpful to me.

Cheers,
Arne

**Comment by cr** [comment]
I will keep asking around, although it will be hard to find digitally-inclined HX870 users who are able and willing to descend into bitland. So unless I end up buying an EU model for myself, please get back in touch once you have access to the radio again. USB capturing with Wireshark is actually pretty simple, and instructions will be easy to compile on short notice.

Until then, do you by any chance still have a factory-default (or nearly factory-default) DAT dump of your EU model around?

Also let me thank you for your amazing reverse-engineering work on the DAT files. I can only imagine how many config changes and DAT dumps it must have taken. It will make the perfect building block for further rev-eng work on the HX870.

**Comment by johannessen** [comment]
Right. Will do. I'm sending the memory dump by email. I'm afraid it's not *quite* factory-default. I had my dealer program the MMSI and some EXP channels for me because I had no idea how hackable this thing would be.

BTW, I checked out Wireshark last night; saving a PCAP dump indeed doesn't seem that difficult.

**Comment by cr** [comment]
I guess near-default will work well as you already identified most of those fields.

If you want to play with Wireshark make sure to install the *USBPCap* package suggested by the Wireshark installer. After reboot, Wireshark should then list two USB capture interfaces on its main screen. It also comes with the versatile command line tool `tshark` which I use for extracting raw USB protocol data from *.pcapng* files for further processing:

```bash
tshark -r $PCAPFILE -2 -R "usb.device_address == $USBDEVADDR && usb.transfer_type == 3" -T fields -e usb.endpoint_address.direction -e usb.capdata
```

**Comment by johannessen** [comment]
Hmm, good point about capturing traffic being more difficult on USB than on other interfaces. USBPCap doesn't appear to be available for the Mac, but capturing USB is [allegedly still possible](https://aud-ios.com/2017/10/22/usb-monitoring-with-wireshark/) (though I couldn't get it to work when I tried just now).

But I run Yaesu's YCE15 software on Windows inside a VirtualBox VM anyway. Guess I could simply install Wireshark + USBPCap inside the VM to save the dump in the Windows guest and still use `tshark` on the OS X host or wherever to analyse it. I'll look into it.

That said, the USB connection to the HX870E shows up as a serial link in OS X when connected. Not sure why. At any rate, it's probably wasted time to try and figure out a solution before I have the radio at hand to actually try it. Pity I didn't take it with me…

**Comment by johannessen** [comment]
I believe we resolved this via email long ago. Do feel free to reopen if that’s not the case.
